-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 12:39:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Dojos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dojos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_modificacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_modificacion` DATETIME NULL,
  `Dojo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Estudiantes_Dojos1_idx` (`Dojo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiantes_Dojos1`
    FOREIGN KEY (`Dojo_id`)
    REFERENCES `mydb`.`Dojos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`intereses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`intereses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_modificacion` DATETIME NULL,
  `Estudiante_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_intereses_Estudiantes1_idx` (`Estudiante_id` ASC) VISIBLE,
  CONSTRAINT `fk_intereses_Estudiantes1`
    FOREIGN KEY (`Estudiante_id`)
    REFERENCES `mydb`.`Estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `calle` VARCHAR(255) NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_modificacion` DATETIME NULL,
  `Estudiante_id` INT NOT NULL,
  `Dojo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Direcciones_Estudiantes1_idx` (`Estudiante_id` ASC) VISIBLE,
  INDEX `fk_Direcciones_Dojos1_idx` (`Dojo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Direcciones_Estudiantes1`
    FOREIGN KEY (`Estudiante_id`)
    REFERENCES `mydb`.`Estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direcciones_Dojos1`
    FOREIGN KEY (`Dojo_id`)
    REFERENCES `mydb`.`Dojos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
